---
sudo: required
language: python
services:
  - docker
install:
  - python3 -m pip install ansible molecule[docker] ansible-lint yamllint
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
