{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
  elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install systemd-udev && dnf clean all; \
  fi
