# This section taken directly from the molecule source
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude && apt-get clean && rm -rf /var/lib/apt/lists/*; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 sudo bash iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 sudo bash ca-certificates iproute2 && xbps-remove -O; fi
# End of section from molecule sources

# Install the systemd udev package. Note that Alpine doesn't use udev, so this
# Ansible role doesn't support Alpine. Void linux uses a fork of the systemd
# udev called eudev. This role hasn't been tested on anything but Fedora, but
# we'll leave these lines present for the future.
RUN if [ $(command -v apt-get) ]; then export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y udev && apt-get clean && rm -rf /var/lib/apt/lists/*; \
  elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install systemd-udev && dnf clean all; \
  elif [ $(command -v yum) ]; then yum makecache fast && yum install -y systemd-udev && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
  elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y udev && zypper clean -a; \
  elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y eudev && xbps-remove -O; fi
