---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    dockerfile: Dockerfile.j2
    image: fedora:33
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
