---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    dockerfile: Dockerfile.j2
    # image: docker.io/pycontribs/centos:8
    image: fedora:latest #docker.io/pycontribs/fedora:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
